---

- hosts: local
  pre_tasks:
    - name: Upgrade the OS (apt-get dist-upgrade)
      tags: always
      become: true
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

  tasks:
  - name: Install nvm
    ansible.builtin.shell: >
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
    args:
      creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

  - name: Install node
    ansible.builtin.shell: >
      /bin/bash -c "source ~/.nvm/nvm.sh && nvm install --lts"
    args:
      creates: "{{ ansible_env.HOME }}/.nvm/alias"

